// Code generated by "stringer -type=ID -trimprefix=ID"; DO NOT EDIT.

package tls

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IDCACertFile-1]
	_ = x[IDCACertPath-2]
	_ = x[IDCiphers-3]
	_ = x[IDClientCertFile-4]
	_ = x[IDCurves-5]
	_ = x[IDInsecureKeyLogFile-6]
	_ = x[IDInsecureSkipVerify-7]
	_ = x[IDKeyFile-8]
	_ = x[IDListCiphers-9]
	_ = x[IDListCurves-10]
	_ = x[IDNextProtos-11]
	_ = x[IDRandom-12]
	_ = x[IDServerName-13]
	_ = x[IDTime-14]
	_ = x[IDTLSv1-15]
	_ = x[IDTLSv1_0-16]
	_ = x[IDTLSv1_1-17]
	_ = x[IDTLSv1_2-18]
	_ = x[IDTLSv1_3-19]
}

const _ID_name = "CACertFileCACertPathCiphersClientCertFileCurvesInsecureKeyLogFileInsecureSkipVerifyKeyFileListCiphersListCurvesNextProtosRandomServerNameTimeTLSv1TLSv1_0TLSv1_1TLSv1_2TLSv1_3"

var _ID_index = [...]uint8{0, 10, 20, 27, 41, 47, 65, 83, 90, 101, 111, 121, 127, 137, 141, 146, 153, 160, 167, 174}

func (i ID) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_ID_index)-1 {
		return "ID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ID_name[_ID_index[idx]:_ID_index[idx+1]]
}
