# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

builds:
  - main: ./cmd/toupee
    id: toupee
    binary: toupee
    <<: &build_defaults
      goos:
        - linux
        - windows
        - darwin
      env:
        - CGO_ENABLED=0
      ldflags:
        - -s -w -X github.com/Carbonfrost/joe-cli-http/internal/build.Version={{.Version}}
  - main: ./cmd/weave
    id: weave
    binary: weave
    <<: *build_defaults

  - main: ./cmd/wig
    id: wig
    binary: wig
    <<: *build_defaults

archives:
  - id: toupee
    builds:
      - toupee
    <<: &archive_defaults
      name_template: >-
        {{ .ProjectName }}_
        {{- title .Os }}_
        {{- if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "386" }}i386
        {{- else }}{{ .Arch }}{{ end }}
        {{- if .Arm }}v{{ .Arm }}{{ end }}
      format_overrides:
        - goos: windows
          format: zip

  - id: weave
    builds:
      - weave
    <<: *archive_defaults

  - id: wig
    builds:
      - wig
    <<: *archive_defaults        

brews:
  - name: toupee
    ids:
    - toupee
    <<: &brew_defaults
      repository: 
        owner: Carbonfrost
        name: homebrew-tap
        token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
      commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
      homepage: "https://github.com/Carbonfrost/joe-cli-http"
    description: "Expands RFC 6570 (level 4) URI templates"
    
  - name: weave
    ids:
    - weave
    description: "Provides access to a simple Go HTTP server for files and proxy handling"
    <<: *brew_defaults

  - name: wig
    ids:
    - wig
    description: "Provides access to the Go HTTP client with some cURL compatibility"
    <<: *brew_defaults

changelog:
  disable: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-dev"
