// Code generated by "stringer -type=ID -trimprefix=ID"; DO NOT EDIT.

package dialer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IDDialTimeout-0]
	_ = x[IDDialKeepAlive-1]
	_ = x[IDDisableDialKeepAlive-2]
	_ = x[IDBindAddress-3]
	_ = x[IDInterface-4]
	_ = x[IDListInterfaces-5]
}

const _ID_name = "DialTimeoutDialKeepAliveDisableDialKeepAliveBindAddressInterfaceListInterfaces"

var _ID_index = [...]uint8{0, 11, 24, 44, 55, 64, 78}

func (i ID) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ID_index)-1 {
		return "ID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ID_name[_ID_index[idx]:_ID_index[idx+1]]
}
