// Code generated by "stringer -type=ID -trimprefix=ID"; DO NOT EDIT.

package httpclient

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IDAuth-1]
	_ = x[IDBaseURL-2]
	_ = x[IDBasicAuth-3]
	_ = x[IDBindAddress-4]
	_ = x[IDBody-5]
	_ = x[IDBodyContent-6]
	_ = x[IDDialKeepAlive-7]
	_ = x[IDDialTimeout-8]
	_ = x[IDDisableDialKeepAlive-9]
	_ = x[IDDNSInterface-10]
	_ = x[IDDownload-11]
	_ = x[IDFailFast-12]
	_ = x[IDFillValue-13]
	_ = x[IDFollowRedirects-14]
	_ = x[IDHeader-15]
	_ = x[IDIncludeResponseHeaders-16]
	_ = x[IDIntegrity-17]
	_ = x[IDInterface-18]
	_ = x[IDJSON-19]
	_ = x[IDJSONContent-20]
	_ = x[IDListAuthenticators-21]
	_ = x[IDListIntegrityAlgorithms-22]
	_ = x[IDListInterfaces-23]
	_ = x[IDMethod-24]
	_ = x[IDNoOutput-25]
	_ = x[IDOutputFile-26]
	_ = x[IDPreferGo-27]
	_ = x[IDQueryString-28]
	_ = x[IDRequestID-29]
	_ = x[IDStrictErrorsDNS-30]
	_ = x[IDStripComponents-31]
	_ = x[IDTraceLevel-32]
	_ = x[IDURITemplateVar-33]
	_ = x[IDURITemplateVars-34]
	_ = x[IDURLValue-35]
	_ = x[IDUser-36]
	_ = x[IDUserAgent-37]
	_ = x[IDVerbose-38]
	_ = x[IDWriteErr-39]
	_ = x[IDWriteOut-40]
}

const _ID_name = "AuthBaseURLBasicAuthBindAddressBodyBodyContentDialKeepAliveDialTimeoutDisableDialKeepAliveDNSInterfaceDownloadFailFastFillValueFollowRedirectsHeaderIncludeResponseHeadersIntegrityInterfaceJSONJSONContentListAuthenticatorsListIntegrityAlgorithmsListInterfacesMethodNoOutputOutputFilePreferGoQueryStringRequestIDStrictErrorsDNSStripComponentsTraceLevelURITemplateVarURITemplateVarsURLValueUserUserAgentVerboseWriteErrWriteOut"

var _ID_index = [...]uint16{0, 4, 11, 20, 31, 35, 46, 59, 70, 90, 102, 110, 118, 127, 142, 148, 170, 179, 188, 192, 203, 221, 244, 258, 264, 272, 282, 290, 301, 310, 325, 340, 350, 364, 379, 387, 391, 400, 407, 415, 423}

func (i ID) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_ID_index)-1 {
		return "ID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ID_name[_ID_index[idx]:_ID_index[idx+1]]
}
