// Code generated by "stringer -type=ID -trimprefix=ID"; DO NOT EDIT.

package uritemplates

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IDPartialExpand-1]
	_ = x[IDTemplate-2]
	_ = x[IDURITemplateVar-3]
	_ = x[IDURITemplateVars-4]
}

const _ID_name = "PartialExpandTemplateURITemplateVarURITemplateVars"

var _ID_index = [...]uint8{0, 13, 21, 35, 50}

func (i ID) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_ID_index)-1 {
		return "ID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ID_name[_ID_index[idx]:_ID_index[idx+1]]
}
