// Code generated by "stringer -type=ID -trimprefix=ID"; DO NOT EDIT.

package httpserver

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IDAccessLog-1]
	_ = x[IDAddr-2]
	_ = x[IDHideDirectoryListings-3]
	_ = x[IDHostname-4]
	_ = x[IDIdleTimeout-5]
	_ = x[IDMaxHeaderBytes-6]
	_ = x[IDOpenInBrowser-7]
	_ = x[IDPort-8]
	_ = x[IDReadHeaderTimeout-9]
	_ = x[IDReadTimeout-10]
	_ = x[IDServerHeader-11]
	_ = x[IDStaticDirectory-12]
	_ = x[IDTLSCertFile-13]
	_ = x[IDTLSKeyFile-14]
	_ = x[IDWriteTimeout-15]
}

const _ID_name = "AccessLogAddrHideDirectoryListingsHostnameIdleTimeoutMaxHeaderBytesOpenInBrowserPortReadHeaderTimeoutReadTimeoutServerHeaderStaticDirectoryTLSCertFileTLSKeyFileWriteTimeout"

var _ID_index = [...]uint8{0, 9, 13, 34, 42, 53, 67, 80, 84, 101, 112, 124, 139, 150, 160, 172}

func (i ID) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_ID_index)-1 {
		return "ID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ID_name[_ID_index[idx]:_ID_index[idx+1]]
}
