// Code generated by "stringer -type=ID -trimprefix=ID"; DO NOT EDIT.

package websocket

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IDBinary-1]
	_ = x[IDCloseTimeout-2]
	_ = x[IDCompression-3]
	_ = x[IDHandshakeTimeout-4]
	_ = x[IDHeader-5]
	_ = x[IDInput-6]
	_ = x[IDMessage-7]
	_ = x[IDMessageType-8]
	_ = x[IDOrigin-9]
	_ = x[IDReadBufferSize-10]
	_ = x[IDReadLimit-11]
	_ = x[IDReadTimeout-12]
	_ = x[IDSubprotocol-13]
	_ = x[IDURLValue-14]
	_ = x[IDVerbose-15]
	_ = x[IDWriteBufferSize-16]
	_ = x[IDWriteTimeout-17]
}

const _ID_name = "BinaryCloseTimeoutCompressionHandshakeTimeoutHeaderInputMessageMessageTypeOriginReadBufferSizeReadLimitReadTimeoutSubprotocolURLValueVerboseWriteBufferSizeWriteTimeout"

var _ID_index = [...]uint8{0, 6, 18, 29, 45, 51, 56, 63, 74, 80, 94, 103, 114, 125, 133, 140, 155, 167}

func (i ID) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_ID_index)-1 {
		return "ID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ID_name[_ID_index[idx]:_ID_index[idx+1]]
}
